Repository hminah0215/tomatoes, pull requests merged in 2024-11, with the labels that each got.

#79 Refactor: 검색창 관련 리팩토링
  src/containers/magazine/TomatoTipItem.tsx
  src/containers/search/SearchHeader.tsx
  src/containers/search/SearchResults.tsx
  src/utils/getTagLabel.ts
Labels: 🎨디자인, 🚀기능 구현, 🛠️기능 수정

#80 Feat, Design, Refactor: Home / Magazine 리팩토링
  package-lock.json
  package.json
  public/assets/noResult/PC_header_tomato.svg
  src/app/magazine/page.tsx
  src/components/common/ActivityContestDescription.tsx
  src/components/common/ActivityContestDetailTab.tsx
  src/components/common/Dday.tsx
  src/components/common/noResult.tsx
  src/containers/home/ActivityCardSlider.tsx
  src/containers/home/BannerLink.tsx
  src/containers/home/ContestCardSlider.tsx
  src/containers/home/Home.tsx
  src/containers/home/HomeGridItem.tsx
  src/containers/home/MainSlider.tsx
  src/containers/home/MoMainSlider.tsx
  src/containers/magazine/TomatoTipItem.tsx
  src/lib/fetchActivityCardSlider.ts
  src/lib/fetchBestPickGridView.ts
  src/lib/fetchContestCardSlider.ts
  src/lib/fetchMainSlider.ts
  src/lib/fetchRecoActivityGridView.ts
  tailwind.config.ts
Labels: 🎨디자인, 🚀기능 구현, 🛠️기능 수정

#81 Refactor: 페이지네이션 관련 리팩토링
  src/app/activity/[id]/page.tsx
  src/app/activity/page.tsx
  src/app/contest/[id]/page.tsx
  src/app/contest/page.tsx
  src/app/globals.css
  src/components/skeleton/ActivityContestItemSkeleton.tsx
  src/components/skeleton/HomeGridItemSkeleton.tsx
  src/components/skeleton/TomatoTipSkeleton.tsx
  src/components/ui/grid/ActivityContestItem.tsx
  src/components/ui/navigation/Navigation.tsx
  src/components/ui/pagination/Pagination.tsx
  src/components/ui/pagination/PaginationOld.tsx
  src/containers/activity/Activity.tsx
  src/containers/activity/ActivityDetail.tsx
  src/containers/contest/Contest.tsx
  src/containers/contest/ContestDetail.tsx
  src/containers/magazine/MtomatoPick.tsx
  src/containers/magazine/TomatoTips.tsx
  src/hooks/useResponsiveItemsPerPage.tsx
  src/hooks/useScroll.tsx
  src/lib/fetchActivityContestDetailWith.ts
  src/lib/fetchPaginatedData.ts
  src/types/data.d.ts
  src/types/grid.d.ts
  src/types/pagination.d.ts
  src/utils/url.ts
Labels: 🎨디자인, 🚀기능 구현, 🛠️기능 수정

#82 1차 리팩토링 이후 배포
  package-lock.json
  package.json
  public/assets/noResult/PC_header_tomato.svg
  src/app/activity/[id]/page.tsx
  src/app/activity/page.tsx
  src/app/contest/[id]/page.tsx
  src/app/contest/page.tsx
  src/app/globals.css
  src/app/magazine/page.tsx
  src/components/common/ActivityContestDescription.tsx
  src/components/common/ActivityContestDetailTab.tsx
  src/components/common/Dday.tsx
  src/components/common/noResult.tsx
  src/components/skeleton/ActivityContestItemSkeleton.tsx
  src/components/skeleton/HomeGridItemSkeleton.tsx
  src/components/skeleton/TomatoTipSkeleton.tsx
  src/components/ui/grid/ActivityContestItem.tsx
  src/components/ui/navigation/Navigation.tsx
  src/components/ui/pagination/Pagination.tsx
  src/components/ui/pagination/PaginationOld.tsx
  src/containers/activity/Activity.tsx
  src/containers/activity/ActivityDetail.tsx
  src/containers/contest/Contest.tsx
  src/containers/contest/ContestDetail.tsx
  src/containers/home/ActivityCardSlider.tsx
  src/containers/home/BannerLink.tsx
  src/containers/home/ContestCardSlider.tsx
  src/containers/home/Home.tsx
  src/containers/home/HomeGridItem.tsx
  src/containers/home/MainSlider.tsx
  src/containers/home/MoMainSlider.tsx
  src/containers/magazine/MtomatoPick.tsx
  src/containers/magazine/TomatoTipItem.tsx
  src/containers/magazine/TomatoTips.tsx
  src/containers/search/SearchHeader.tsx
  src/containers/search/SearchResults.tsx
  src/hooks/useResponsiveItemsPerPage.tsx
  src/hooks/useScroll.tsx
  src/lib/fetchActivityCardSlider.ts
  src/lib/fetchActivityContestDetailWith.ts
  src/lib/fetchBestPickGridView.ts
  src/lib/fetchContestCardSlider.ts
  src/lib/fetchMainSlider.ts
  src/lib/fetchPaginatedData.ts
  src/lib/fetchRecoActivityGridView.ts
  src/types/data.d.ts
  src/types/grid.d.ts
  src/types/pagination.d.ts
  src/utils/getTagLabel.ts
  src/utils/url.ts
  tailwind.config.ts
Labels: 🎸기타

#87 Refactor: 매거진 리팩토링
  .github/workflows/crawler.yml
  src/app/api/uploadMagazine/route.ts
  src/app/magazine/page.tsx
  src/app/magazine/tomatoTip/page.tsx
  src/containers/magazine/CurrentHighlights.tsx
  src/containers/magazine/MtomatoPick.tsx
  src/containers/magazine/TomatoTips.tsx
  src/lib/fetchBestPickGridView.ts
  src/lib/fetchPaginatedData.ts
Labels: 🎨디자인, 🎸기타, 🛠️기능 수정

#88 Design, Refactor: Home/Magazine Refactoring ver.2
  src/components/ui/grid/ActivityContestItem.tsx
  src/containers/activity/ActivityDetail.tsx
  src/containers/contest/ContestDetail.tsx
  src/containers/home/ActivityCardSlider.tsx
  src/containers/home/ContestCardSlider.tsx
  src/containers/home/HomeGridItem.tsx
  src/containers/home/MainSlider.tsx
  src/containers/home/MoMainSlider.tsx
  src/lib/fetchBestPickGridView.ts
  src/types/data.d.ts
  src/utils/format.ts
Labels: 🎨디자인, 🛠️기능 수정

#89 Refactor: 공모전 및 대외활동 페이지
  src/app/activity/[id]/page.tsx
  src/app/activity/layout.tsx
  src/app/activity/loading.tsx
  src/app/activity/page.tsx
  src/app/contest/[id]/page.tsx
  src/app/contest/layout.tsx
  src/app/contest/loading.tsx
  src/app/contest/page.tsx
  src/components/skeleton/ActivityContestItemSkeleton.tsx
  src/components/skeleton/ActivityContestSkeleton.tsx
  src/components/skeleton/CategoryHeaderSkeleton.tsx
  src/components/ui/grid/ActivityContestItem.tsx
  src/components/ui/navigation/Navigation.tsx
  src/containers/activity/Activity.tsx
  src/containers/contest/Contest.tsx
  src/containers/home/HomeGridItem.tsx
  src/hooks/useScroll.tsx
Labels: 🎨디자인, 🚀기능 구현, 🛠️기능 수정

#90 Design: 반응형 CSS 작업
  src/app/intro/page.tsx
  src/components/common/Header.tsx
  src/components/common/SearchBar.tsx
  src/components/common/TabItem.tsx
  src/containers/search/SearchCategory.tsx
  src/containers/search/SearchHeader.tsx
  src/containers/search/SearchResults.tsx
Labels: 🎨디자인, 🛠️기능 수정

#91 2차 리팩토링 배포
  .github/workflows/crawler.yml
  package-lock.json
  package.json
  src/app/activity/[id]/page.tsx
  src/app/activity/layout.tsx
  src/app/activity/loading.tsx
  src/app/activity/page.tsx
  src/app/api/uploadMagazine/route.ts
  src/app/contest/[id]/page.tsx
  src/app/contest/layout.tsx
  src/app/contest/loading.tsx
  src/app/contest/page.tsx
  src/app/intro/page.tsx
  src/app/magazine/page.tsx
  src/app/magazine/tomatoTip/page.tsx
  src/components/common/Header.tsx
  src/components/common/SearchBar.tsx
  src/components/common/TabItem.tsx
  src/components/skeleton/ActivityContestItemSkeleton.tsx
  src/components/skeleton/ActivityContestSkeleton.tsx
  src/components/skeleton/CategoryHeaderSkeleton.tsx
  src/components/ui/grid/ActivityContestItem.tsx
  src/components/ui/navigation/Navigation.tsx
  src/components/ui/pagination/Pagination.tsx
  src/components/ui/pagination/PaginationOld.tsx
  src/containers/activity/Activity.tsx
  src/containers/activity/ActivityDetail.tsx
  src/containers/contest/Contest.tsx
  src/containers/contest/ContestDetail.tsx
  src/containers/home/ActivityCardSlider.tsx
  src/containers/home/ContestCardSlider.tsx
  src/containers/home/HomeGridItem.tsx
  src/containers/home/MainSlider.tsx
  src/containers/home/MoMainSlider.tsx
  src/containers/magazine/CurrentHighlights.tsx
  src/containers/magazine/MtomatoPick.tsx
  src/containers/magazine/TomatoTips.tsx
  src/containers/search/SearchCategory.tsx
  src/containers/search/SearchHeader.tsx
  src/containers/search/SearchResults.tsx
  src/hooks/useScroll.tsx
  src/lib/fetchBestPickGridView.ts
  src/lib/fetchPaginatedData.ts
  src/types/data.d.ts
  src/utils/format.ts
  tailwind.config.ts
Labels: 🎸기타
