Repository hminah0215/tomatoes, pull requests merged in 2024-10, with the labels that each got.

#2 feat : 반응형 footer 생성 [#1]
  src/app/globals.css
  src/components/common/Footer.tsx
Labels: 🎨디자인, 🚀기능 구현

#4 Feat: 공용 컴포넌트 Search Bar 구현 작업
  package-lock.json
  package.json
  src/components/common/SearchBar.tsx
Labels: 🎨디자인, 🚀기능 구현

#6 Feat: 공통 컴포넌트 중 태그, 디데이 구현
  package-lock.json
  package.json
  src/app/page.tsx
  src/components/common/Dday.tsx
  src/components/common/Tag.tsx
  tailwind.config.ts
  tsconfig.json
Labels: 🎨디자인, 🚀기능 구현

#8 Design: 공용 컴포넌트 레이아웃 구현
  src/app/globals.css
  src/app/layout.tsx
  src/components/common/BannerLink.tsx
  src/components/ui/Header.tsx
  src/components/ui/NavItem.tsx
  src/components/ui/Navigation.tsx
Labels: 🎨디자인, 🎸기타

#12 Feat. 404 페이지 구현
  public/assets/common/MO_404_t.svg
  public/assets/common/PC_404_t.svg
  src/app/not-found.tsx
Labels: 🎨디자인, 🚀기능 구현

#15 Feat: '통신 오류' 페이지 구현 작업
  public/assets/common/PC_net_err_t.svg
  public/assets/common/PC_net_err_wifi.svg
  src/app/page.tsx
  src/components/common/NetworkError.tsx
Labels: 🎨디자인, 🚀기능 구현

#14 Feat: '검색 결과 없음' 페이지 구현 작업
  public/assets/noResult/PC_header_t.svg
  public/assets/noResult/PC_logo_t.svg
  src/components/common/Dday.tsx
  src/components/common/Tag.tsx
  src/components/noResult.tsx
Labels: 🎨디자인

#16 Feat: 페이지네이션 컴포넌트 구현
  public/assets/pagination/Pagination_first.svg
  public/assets/pagination/Pagination_last.svg
  public/assets/pagination/Pagination_next.svg
  public/assets/pagination/Pagination_prev.svg
  public/assets/test_image.png
  src/app/activity/page.tsx
  src/app/contest/page.tsx
  src/app/page.tsx
  src/components/ui/grid/GridItem.tsx
  src/components/ui/grid/GridView.tsx
  src/components/ui/pagination/Pagination.tsx
  src/components/ui/pagination/PaginationControl.tsx
  src/types/types.d.ts
Labels: 🎨디자인, 🚀기능 구현

#18 Feat: 홈 화면 디자인 작업 1차
  public/assets/homePage/MO_banner.svg
  public/assets/homePage/PC_banner.svg
  public/assets/homePage/PC_recommendationMark_t.svg
  public/fonts/Recipekorea.ttf
  src/app/globals.css
  src/app/page.tsx
  src/components/common/Dday.tsx
  src/components/ui/grid/GridItem.tsx
  src/components/ui/homePage/ContestBanner.tsx
  src/components/ui/pagination/PaginationForHome.tsx
  tailwind.config.ts
Labels: 🎨디자인, 🚀기능 구현

#23 Feat: 매거진 - 토마토 팁 데이터 크롤링 및 db 업로드
  src/app/api/uploadData/route.ts
  src/scripts/magazine-crawling.py
  src/scripts/tomatoTip_data.json
  src/types/supabase.ts
Labels: 🚀기능 구현

#25 Feat: 매거진 페이지 디자인 (추후 수정예정)
  public/assets/magazine/MO_gallary_tomato.svg
  public/assets/magazine/MO_magazine_banner.svg
  public/assets/magazine/MO_tips_thumbnail_1.svg
  public/assets/magazine/MO_tips_thumbnail_2.svg
  public/assets/magazine/MO_tips_thumbnail_3.svg
  public/assets/magazine/Mo_report_tomato.svg
  public/assets/magazine/PC_gallary_tomato.svg
  public/assets/magazine/PC_magazine_banner.svg
  public/assets/magazine/PC_report_tomato.svg
  public/assets/magazine/PC_tips_thumbnail_1.svg
  public/assets/magazine/PC_tips_thumbnail_2.svg
  public/assets/magazine/PC_tips_thumbnail_3.svg
  src/app/magazine/components/CurrentHighlights.tsx
  src/app/magazine/components/MReportCoustomAlert.tsx
  src/app/magazine/components/MagazineHeader.tsx
  src/app/magazine/components/MagazineList.tsx
  src/app/magazine/components/MagazineReport.tsx
  src/app/magazine/components/TomatoTips.tsx
  src/app/magazine/layout.tsx
  src/app/magazine/magazineGallary/page.tsx
  src/app/magazine/magazineReport/page.tsx
  src/app/magazine/page.tsx
  src/app/magazine/tomatoTip/page.tsx
  src/components/common/MagazineSearchBar.tsx
Labels: 🎨디자인, 🚀기능 구현

#26 Feat: 공고등록/문의 페이지 디자인
  public/assets/cs/PC_business_banner_t.svg
  public/assets/cs/PC_business_t.svg
  public/assets/cs/PC_sidebar_t.svg
  public/assets/intro/PC_banner (1).svg
  public/assets/intro/PC_banner (2).svg
  public/assets/intro/PC_grid_t (1).svg
  public/assets/intro/PC_grid_t (2).svg
  public/assets/intro/PC_grid_t (3).svg
  src/app/cs/components/AdInquiry.tsx
  src/app/cs/components/BusinessIntro.tsx
  src/app/cs/components/LegalNotice.tsx
  src/app/cs/components/SideBar.tsx
  src/app/cs/components/Terms.tsx
  src/app/cs/components/TomatoReport.tsx
  src/app/cs/page.tsx
  src/app/intro/page.tsx
  src/components/common/Footer.tsx
Labels: 🎨디자인, 🚀기능 구현

#27 Feat: 공모전 및 대외활동 페이지 디자인
  package-lock.json
  package.json
  public/assets/common/MO_reset.svg
  public/assets/common/PC_reset.svg
  public/assets/common/tag_active.svg
  src/app/activity/components/CategoryPanel.tsx
  src/app/activity/components/FilterItem.tsx
  src/app/activity/components/ResetButton.tsx
  src/app/activity/components/TabItem.tsx
  src/app/activity/page.tsx
  src/app/contest/components/CategoryPanel.tsx
  src/app/contest/components/FilterItem.tsx
  src/app/contest/components/ResetButton.tsx
  src/app/contest/components/TabItem.tsx
  src/app/contest/page.tsx
  src/app/talk/page.tsx
  src/components/ui/Navigation.tsx
  src/components/ui/grid/GridView.tsx
  src/components/ui/pagination/Pagination.tsx
  src/constants/consts.ts
  src/store/store.ts
  src/types/types.d.ts
  tailwind.config.ts
Labels: 🎨디자인, 🎸기타

#28 Feat: 홈 화면 디자인 작업 마무리
  public/assets/homePage/Activity_1.png
  public/assets/homePage/Activity_2.png
  public/assets/homePage/Activity_3.png
  public/assets/homePage/Contest1.png
  public/assets/homePage/Contest2.png
  public/assets/homePage/Main_Poster1.png
  public/assets/homePage/Main_Poster2.png
  src/app/page.tsx
  src/components/ui/homePage/ActivityCardSlider.tsx
  src/components/ui/homePage/ContestCardSlider.tsx
  src/components/ui/homePage/MainSlider.tsx
  src/components/ui/pagination/PaginationForHome.tsx
Labels: 🎨디자인, 🚀기능 구현

#37 공모전, 대외활동 크롤링 파이썬 코드 수정
  src/scripts/activity_1024.json
  src/scripts/activity_1027.json
  src/scripts/color.py
  src/scripts/contest_1024.json
  src/scripts/contest_1027.json
  src/scripts/pick-crawling.py
  src/scripts/tomatoTip-crawling.py
Labels: 🎸기타, 🚀기능 구현

#42 Feat: 공통 페이지네이션 및 그리드 컴포넌트 구현
  src/app/activity/page.tsx
  src/app/contest/page.tsx
  src/app/not-found.tsx
  src/components/ui/grid/ActivityContestItem.tsx
  src/components/ui/grid/GridItem.tsx
  src/components/ui/grid/GridView.tsx
  src/components/ui/grid/GridViewTest.tsx
  src/components/ui/pagination/Pagination.tsx
  src/components/ui/pagination/PaginationForHome.tsx
  src/containers/home/Home.tsx
  src/containers/home/HomeGridItem.tsx
  src/containers/magazine/TomatoTips.tsx
  src/hooks/useResponsiveItemsPerPage.tsx
  src/types/grid.d.ts
  src/types/types.d.ts
  src/utils/format.ts
Labels: 🎨디자인, 🎸기타, 🚀기능 구현, 🛠️기능 수정

#43 Feat. 매거진 상세페이지 구현
  public/assets/magazine/MO_mzDetail_banner.svg
  public/assets/magazine/PC_mzDetail_banner.svg
  public/assets/magazine/PC_mzDetail_left.svg
  public/assets/magazine/PC_mzDetail_right.svg
  src/app/api/uploadMagazine/route.ts
  src/app/magazine/layout.tsx
  src/app/magazine/page.tsx
  src/app/magazine/tomatoTip/[id]/page.tsx
  src/containers/magazine/CurrentHighlights.tsx
  src/containers/magazine/MagazineHeader.tsx
  src/containers/magazine/TomatoTipDetail.tsx
  src/containers/magazine/TomatoTips.tsx
  src/lib/fetchTomatoTip.ts
  src/scripts/tomatoTip-crawling.py
  src/scripts/tomatoTip_data.json
Labels: 🎨디자인, 🚀기능 구현, 🛠️기능 수정

#46 Design: 토마토들 소개 페이지 구현
  public/assets/intro/PC_grid_t (4).svg
  public/assets/intro/PC_grid_t (5).svg
  public/assets/intro/PC_grid_t (6).svg
  public/assets/intro/PC_grid_t (7).svg
  public/assets/intro/PC_grid_t (8).svg
  public/assets/intro/PC_grid_t (9).svg
  public/assets/intro/PC_letter_t.svg
  public/assets/intro/PC_triple_t.svg
  src/app/intro/page.tsx
  src/app/search/page.tsx
  src/constants/consts.ts
  src/containers/search/SearchHeader.tsx
  src/containers/search/SearchResults.tsx
  src/lib/fetchSearchResults.ts
Labels: 🎨디자인

#47 Feat: 공모전 및 대외활동 데이터 크롤링 작업
  package-lock.json
  package.json
  src/app/api/uploadData/route.ts
  src/components/ui/grid/GridView.tsx
  src/lib/supabaseUtils.ts
  src/scripts/activity_contest.json
  src/scripts/pick-crawling.py
  src/types/data.d.ts
  src/types/grid.d.ts
  src/utils/format.ts
Labels: 🎸기타, 🚀기능 구현, 🛠️기능 수정

#54 Feat: 공통 탭바 구현
  src/app/activity/[id]/page.tsx
  src/app/activity/layout.tsx
  src/app/activity/page.tsx
  src/app/contest/[id]/page.tsx
  src/app/contest/layout.tsx
  src/app/contest/page.tsx
  src/app/magazine/layout.tsx
  src/app/magazine/magazineGallery/page.tsx
  src/components/common/CategoryHeader.tsx
  src/components/common/TabItem.tsx
  src/components/common/TabMenu.tsx
  src/components/common/TabMenuItem.tsx
  src/components/ui/navigation/Navigation.tsx
  src/containers/activity/ActivityDetail.tsx
  src/containers/activity/CategoryPanel.tsx
  src/containers/activity/TabItem.tsx
  src/containers/contest/CategoryPanel.tsx
  src/containers/search/SearchHeader.tsx
Labels: 🎨디자인, 🚀기능 구현, 🛠️기능 수정

#57 Feat: 검색 페이지 기능 구현
  public/assets/noResult/PC_header_t.svg
  src/app/layout.tsx
  src/app/search/page.tsx
  src/components/common/Header.tsx
  src/components/common/SearchBar.tsx
  src/components/common/noResult.tsx
  src/containers/activity/CategoryPanel.tsx
  src/containers/contest/CategoryPanel.tsx
  src/containers/search/SearchContent.tsx
  src/containers/search/SearchHeader.tsx
  src/containers/search/SearchResults.tsx
  src/lib/fetchSearchResults.ts
  src/types/search.d.ts
Labels: 🎨디자인, 🚀기능 구현

#56 Feat. 매거진 - 토마토 Pick 구현, 크롤링 코드 수정
  src/app/api/uploadMagazine/route.ts
  src/app/layout.tsx
  src/app/magazine/page.tsx
  src/containers/magazine/MagazineList.tsx
  src/containers/magazine/MtomatoPick.tsx
  src/containers/magazine/TomatoTipItem.tsx
  src/lib/fetchBestPickGridView.ts
  src/lib/fetchTomatoTip.ts
  src/scripts/tomatoTip-crawling.py
  src/scripts/tomatoTip_data.json
  src/types/supabase.ts
  src/types/tomatoTips.ts
Labels: 🎨디자인, 🚀기능 구현, 🛠️기능 수정

#63 Feat: 공모전 및 대외활동 상세 페이지 구현
  package-lock.json
  src/app/activity/[id]/page.tsx
  src/app/contest/[id]/page.tsx
  src/components/common/ActivityContestDescription.tsx
  src/components/common/ActivityContestDetailTab.tsx
  src/components/common/CategoryHeader.tsx
  src/components/common/FilterPanel.tsx
  src/components/common/SortPanel.tsx
  src/containers/activity/ActivityDetail.tsx
  src/containers/contest/ContestDetail.tsx
  src/lib/fetchActivityContestDetailWith.ts
Labels: 🎨디자인, 🚀기능 구현

#64 design: 홈 화면 레이아웃 / 매거진 페이지 css / ‘검색어 없음’ 페이지 쿼리 수정
  src/app/magazine/page.tsx
  src/app/magazine/tomatoTip/[id]/page.tsx
  src/app/magazine/tomatoTip/page.tsx
  src/app/search/page.tsx
  src/components/common/Dday.tsx
  src/components/common/SearchBar.tsx
  src/components/common/noResult.tsx
  src/components/ui/pagination/Pagination.tsx
  src/containers/home/ActivityCardSlider.tsx
  src/containers/home/BannerLink.tsx
  src/containers/home/ContestCardSlider.tsx
  src/containers/home/Home.tsx
  src/containers/home/HomeGridItem.tsx
  src/containers/home/MainSlider.tsx
  src/containers/home/MoMainSlider.tsx
  src/containers/magazine/CurrentHighlights.tsx
  src/containers/magazine/MtomatoPick.tsx
  src/containers/magazine/TomatoTipItem.tsx
  src/containers/magazine/TomatoTips.tsx
  src/containers/search/SearchResults.tsx
Labels: 🎨디자인, 🚀기능 구현

#69 매거진 점검, github actions 설정 ... etc
  .github/workflows/crawler.yml.disabled
  public/assets/common/MO_search_t.svg
  src/app/api/uploadMagazine/route.ts
  src/app/magazine/layout.tsx
  src/app/magazine/page.tsx
  src/app/magazine/tomatoTip/[id]/page.tsx
  src/components/common/MagazineSearchBar.tsx
  src/components/common/SearchBar.tsx
  src/components/ui/grid/GridSlideView.tsx
  src/containers/magazine/MagazineHeader.tsx
  src/containers/magazine/MagazineReport.tsx
  src/containers/magazine/MtomatoPick.tsx
  src/containers/magazine/TomatoTipDetail.tsx
  src/containers/magazine/TomatoTipItem.tsx
  src/containers/magazine/TomatoTips.tsx
  src/lib/fetchTomatoTip.ts
  src/scripts/activity_1027.json
  src/scripts/contest_1027.json
  src/scripts/requirements.txt
Labels: 🎨디자인, 🎸기타, 🚀기능 구현, 🛠️기능 수정

#71 Refactor: 발표 전 리팩토링
  src/app/activity/page.tsx
  src/app/contest/[id]/page.tsx
  src/app/contest/page.tsx
  src/components/ui/navigation/NavItem.tsx
  src/components/ui/navigation/Navigation.tsx
  src/containers/activity/Activity.tsx
  src/containers/activity/ActivityDetail.tsx
  src/containers/contest/Contest.tsx
  src/containers/contest/ContestDetail.tsx
  src/lib/fetchActivityAbstractWith.ts
  src/lib/fetchActivityContestDetailWith.ts
  src/types/types.d.ts
Labels: 🛠️기능 수정

#72 Feat: 대외활동, 공모전 검색 기능 구현
  src/app/cs/page.tsx
  src/app/search/page.tsx
  src/components/common/SearchBar.tsx
  src/constants/consts.ts
  src/containers/cs/AdInquiry.tsx
  src/containers/cs/LegalNotice.tsx
  src/containers/cs/SideBar.tsx
  src/containers/cs/Terms.tsx
  src/containers/cs/TomatoReport.tsx
  src/containers/search/SearchCategory.tsx
  src/containers/search/SearchDdayDisplay.tsx
  src/containers/search/SearchResults.tsx
  src/lib/fetchSearchResults.ts
  src/types/data.d.ts
  src/types/search.d.ts
  src/utils/calculateRelevanceScore.ts
Labels: 🎨디자인, 🚀기능 구현

#70 refactor: 각종 css 수정 및 컴포넌트 연결
  src/app/activity/[id]/page.tsx
  src/app/api/uploadData/route.ts
  src/app/api/uploadMagazine/route.ts
  src/app/contest/page.tsx
  src/app/layout.tsx
  src/app/magazine/magazineGallery/page.tsx
  src/app/magazine/page.tsx
  src/app/magazine/tomatoTip/[id]/page.tsx
  src/app/not-found.tsx
  src/app/search/page.tsx
  src/components/common/CategoryHeader.tsx
  src/components/common/Dday.tsx
  src/components/common/FilterPanel.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/common/NetworkError.tsx
  src/components/common/SearchBar.tsx
  src/components/common/TabMenu.tsx
  src/components/common/noResult.tsx
  src/components/ui/grid/GridSlideView.tsx
  src/components/ui/grid/GridView.tsx
  src/components/ui/navigation/Navigation.tsx
  src/components/ui/pagination/Pagination.tsx
  src/components/ui/pagination/PaginationControl.tsx
  src/constants/consts.ts
  src/containers/activity/ActivityDetail.tsx
  src/containers/cs/AdInquiry.tsx
  src/containers/cs/BusinessIntro.tsx
  src/containers/cs/LegalNotice.tsx
  src/containers/cs/SideBar.tsx
  src/containers/cs/Terms.tsx
  src/containers/home/ActivityCardSlider.tsx
  src/containers/home/ContestBanner.tsx
  src/containers/home/ContestCardSlider.tsx
  src/containers/home/Home.tsx
  src/containers/home/HomeGridItem.tsx
  src/containers/home/MainSlider.tsx
  src/containers/magazine/CurrentHighlights.tsx
  src/containers/magazine/MagazineReport.tsx
  src/containers/magazine/MtomatoPick.tsx
  src/containers/magazine/TomatoTipDetail.tsx
  src/containers/magazine/TomatoTipItem.tsx
  src/containers/magazine/TomatoTips.tsx
  src/containers/search/SearchContent.tsx
  src/containers/search/SearchHeader.tsx
  src/hooks/useResponsiveItemsPerPage.tsx
  src/lib/fetchActivityAbstractWith.ts
  src/lib/fetchActivityCardSlider.ts
  src/lib/fetchActivityContestAbstracts.ts
  src/lib/fetchActivityContestDetailWith.ts
  src/lib/fetchBestPickGridView.ts
  src/lib/fetchContestCardSlider.ts
  src/lib/fetchMainSlider.ts
  src/lib/fetchRecoActivityGridView.ts
  src/lib/fetchTomatoTip.ts
  src/types/data.d.ts
  src/types/grid.d.ts
Labels: 🎨디자인, 🚀기능 구현, 🛠️기능 수정
